Instance_Name: "test_gpu_instance"
Instance_Type: "t2.medium"
#Ami_Id: "ami-0c65adc9a5c1b5d7c"
Ami_Id: "ami-03f65b8614a860c29"
#Ami_Id: "ami-0f5ee92e2d63afc18"
Action: "CREATE"
#Action: "TERMINATE"
Pytorch: "1.12"
Python: "3.8"
CUDA: "11.3"
KEY_NAME: "prateek"
Instance_id: "i-030766099c4bf7875"
Instance_Active_Window: ""
